# Generated by Django 4.1.5 on 2023-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reminder', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
